---

## https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

dist: 'xenial'

addons:
  apt:
    packages:
      ## Install Java8 as required by vnu.jar
      - 'openjdk-8-jre'

language: 'node_js'
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - 'node'

install:
  - 'make dependencies-user-wide-get'
  - 'make dependencies-get'
  - 'pip install --user html5validator yq'

script:
  - "make check-full"
