name: Deploy to Uberspace
on: [push]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: pull master and restart
      uses: appleboy/ssh-action@master
      with:
        script: cd ~/servers/api/; git pull; supervisorctl restart api2_daemon
        username: ${{ secrets.USER }}
        host: ${{ secrets.HOST }}
        key: ${{ secrets.PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        # fingerprint: ${{ secrets.FINGERPRINT }}
        debug: false
