name: Deploy to Uberspace

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pull master and restart
        uses: appleboy/ssh-action@master
        with:
          command: cd ~/servers/api/; git pull; supervisorctl restart api2_daemon
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.PRIVATE_KEY }}
