name: Deploy to Uberspace

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pull master and restart
        uses: JimCronqvist/action-ssh@master
        with:
          command: cd ~/servers/api/; git pull; supervisorctl restart api2_daemon
          hosts: ${{ secrets.USER }}@${{ secrets.HOST }}
          #username: ${{ secrets.USER }}
          #passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          debug: true
