name: Deploy to Uberspace
on: [push]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: pull master and restart
      uses: appleboy/ssh-action@master
      env:
        script: whoami
        username: ${{ secrets.USER }}
        host: ${{ secrets.HOST }}
        key: ${{ secrets.PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        fingerprint: ${{ secrets.FINGERPRINT }}
