name: Deploy to Uberspace
on: [push]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: pull master and restart
      uses: appleboy/ssh-action@master
      env:
        USERNAME: ${{ secrets.USER }}
        HOST: ${{ secrets.HOST }}
        SCRIPT: ls -a
        KEY: ${{ secrets.PRIVATE_KEY }}
